### ISSUE TITLE
Concerning the LPID rule book

### ISSUE THREAD

**Issue by bartbink** [EWC-consortium/eudi-wallet-rulebooks-and-schemas#15]
To be added in the rule book: The two attributes of the LPID are atomic, that means they are always presented together as a unit.

**Comment by michelleludovici1** [comment]
This is written in https://github.com/EWC-consortium/eudi-wallet-rfcs/blob/97cb5d043eead6c00575873a7a703bfc9e19ea51/ewc-rfc005-issue-legal-person-identification-data.md to which the rulebook refers.
