### ISSUE TITLE
Legal representative shall be OneOf instead of Anyof in eu-company-certificate schema defintion

### ISSUE THREAD

**Issue by lalc** [EWC-consortium/eudi-wallet-rulebooks-and-schemas#5]
In the [eu-company-certificate schema definition](https://github.com/EWC-consortium/eudi-wallet-rulebooks-and-schemas/blob/main/data-schemas/eu-company-certificate), the legal representation shall be Oneof instead of AnyOf

Affected Lines: 
https://github.com/EWC-consortium/eudi-wallet-rulebooks-and-schemas/blob/d046dc5c37b37d4cae25df15dcb90ca45efb42db/data-schemas/eu-company-certificate#L49-L62

**Comment by celiacouson** [comment]
I am not sure Oneof allows us to have several legal representative who can be either a physical or a legal person. Can you confirm ?
